// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const hasEnv = Boolean(SUPABASE_URL) && Boolean(SUPABASE_PUBLISHABLE_KEY);

export const supabase = hasEnv
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : ({
      auth: {
        getUser: async () => ({ data: { user: null } }),
        getSession: async () => ({ data: { session: null } }),
        onAuthStateChange: (_cb: any) => ({ data: { subscription: { unsubscribe: () => {} } } }),
        signOut: async () => ({ error: null }),
        signInWithPassword: async (_opts: any) => ({ data: { session: null }, error: { message: "Supabase não configurado (VITE_SUPABASE_URL/PUBLISHABLE_KEY)" } }),
        signUp: async (_opts: any) => ({ data: { user: null }, error: { message: "Supabase não configurado (VITE_SUPABASE_URL/PUBLISHABLE_KEY)" } })
      },
      from: () => ({
        select: async () => ({ data: [], error: null }),
        insert: async () => ({ error: null }),
        delete: async () => ({ error: null }),
        update: async () => ({ error: null })
      })
    } as any);
